swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '401': 
          description: Unauthorized
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts:
    get:
      tags:
      - User Accounts
      summary: Display all Accounts
      description: API for getting all accounts
      parameters:
      - in: body
        name: body
        description: Get user accounts
        required: true
        schema:
            $ref: '#/definitions/Transactions'
      responses:
        '200':
          description: User accounts
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request.
        '500':
          description: Internal Server Error
  /user/accounts/{accountsId}:
    get:
      tags:
      - User Accounts
      summary: Display single account
      description: API for getting single account
      parameters:
      - in: path
        name: accountsId
        description: account's ID
        required: true
        type: integer
      - in: body
        name: body
        description: Get user accounts
        required: true
        schema:
            $ref: '#/definitions/Transactions'
      responses:
        '200':
          description: User accounts
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request.
        '500':
          description: Internal Server Error
  /user/accounts/{accountsId}/transactions:
    get:
      tags:
      - User Transactions
      summary: Display all transactions for the current month
      description: API for getting all transactions for the current month
      parameters:
      - in: path
        name: accountsId
        description: account's ID
        required: true
        type: integer
      - in: body
        name: body
        description: Get user accounts by month
        required: true
        schema:
            $ref: '#/definitions/Transactions'
      responses:
        '200':
          description: User accounts by month retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request.
        '500':
          description: Internal Server Error
  /user/accounts/{accountsId}/transactions/{transactionsId}:
    get:
      tags:
      - User Transactions
      summary: Transaction details
      description: API for getting a single transaction details
      parameters:
      - in: path
        name: accountsId
        description: account's ID
        required: true
        type: integer
      - in: path
        name: transactionsId
        description: Transaction's ID
        required: true
        type: integer
      - in: body
        name: body
        description: Get user accounts by month
        required: true
        schema:
            $ref: '#/definitions/Transactions'
      responses:
        '200':
          description: Transaction retrieved successully
          schema:
            $ref: '#/definitions/TransactionsDetails'
        '400':
          description: Bad request.
        '404':
          description: Not Found.
        '500':
          description: Internal Server Error
    put:
      tags:
      - User Transactions
      summary: Update category or notes
      description: API for updating a transaction's category or notes from transaction
      produces:
        - application/json
      parameters:
      - in: path
        name: accountsId
        description: account's ID
        required: true
        type: integer
      - in: path
        name: transactionsId
        description: Transaction's ID
        required: true
        type: integer
      responses:
        '200':
          description: Transaction updated successully'
          schema:
            $ref: '#/definitions/UpdateTransaction'
        '400':
          description: Bad request.
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Transactions:
    type: object
    properties:
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
  TransactionsDetails:
    type: object
    properties:
      transactionsId:
        type: integer
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      type:
        type: string
      category:
        type: string
      notes:
        type: string
  UpdateTransaction:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string